name: Feature request
description: Suggest something new
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the situation where you wished Frame did something it doesn't.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like?
      description: Describe the feature or behavior you're imagining.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Anything else you've tried or thought about.
